# Generated by Django 3.1.4 on 2021-01-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jtext', models.CharField(max_length=200)),
                ('etext', models.CharField(max_length=200)),
            ],
        ),
    ]
